### ISSUE TITLE
关于Lab0结构选择

### ISSUE THREAD

**Issue by chuliyuoujian** [Kosthi/CS144-2024#3]
我还有一个问题，大佬 就是为我看您在lab0中使用了deque string这样的结构，我在Lab0中使用了deque char 这样的结构，但是这种结构会出现为问题，我看网上说是因为string_view返回的应该是一段类似连续内存的东西，但是deque多次插入和删除之后内存可能不连续，您的这个结构也是为了避免这个问题吗? 为了能正常使用我将他给的string_view改成了string但是我的性能测试就是关于速度的测试是跑不过的 我想问一下string_view会造成，这么大的影响吗?(我觉得主要是因为我虚拟机的问题)

**Comment by Kosthi** [comment]
可以看下这个issue #1，你的理解基本对的，如果用 deque char 会因为连续内存的问题用不了 string_view。string_view 可以减少一些字符串拷贝开销，实验 0 性能的瓶颈也是字符串拷贝，这里对字符串的处理应该用移动语义或 string_view 等操作来尽量减少拷贝。具体改成 string 能不能过没测过，我本地试试，但效率肯定会变低。

**Comment by chuliyuoujian** [comment]
好的 太感谢了 我觉得我这个速度直接变成0.06有点太离谱了哈哈哈

**Comment by Kosthi** [comment]
> 好的 太感谢了 我觉得我这个速度直接变成0.06有点太离谱了哈哈哈

我这里是差不多从 35 Gbit/s 降低到 5 Gbit/s。

**Comment by chuliyuoujian** [comment]
OKK谢谢 真的差了这么多呀  知道啦      另外您知道什么原因导致不同机器上面速度差这么多吗 因为我的机器上只有0.06G/s

**Comment by Kosthi** [comment]
> OKK谢谢 真的差了这么多呀 知道啦 另外您知道什么原因导致不同机器上面速度差这么多吗 因为我的机器上只有0.06G/s

虚拟机配置和实机配置。你是用的wsl么，用wsl会快点吧

**Comment by chuliyuoujian** [comment]
我是在ubuntu下跑的 可能会慢很多
